### ISSUE TITLE
Flag stop to show

### ISSUE THREAD

**Issue by curdaneta** [i07/uebersicht-widget-public_ip#1]
Hello

Since a couple of days, the country flag stoped to show. 

script.sh > https://ipapi.co/$IP/country/  returns "Throttled"

Regards
Ciro

**Comment by i07** [comment]
Hi Ciro,

My guess, it might be they made a change, that results in the error message, I've reached out to them and see if it's a bug on their end, all the other endpoints don't seem affected. and the free anonymous account states 1000 requests per day.

for now i'll wait for the response, if it won't resolve, i'll have a look and see if I can find another free api that can return country from ip.

Cheers,
Marc

**Comment by curdaneta** [comment]
Thanks Mark, I'll be waiting if you find a way to fix it
Cheers
Ciro

**Comment by QuattroGam3r** [comment]
Noticed same thing here about a week ago. Seems the issue is actually being returned as "throttled" from `https://ipapi.co/$IP/country/`. I instead switched to `ipinfo.io/$IP/country/` and the flag has returned.

**Comment by i07** [comment]
@curdaneta @QuattroGam3r -- It seems ipapi.co have fixed the issue, the service is back up again.

@QuattroGam3r thanks for the info, if ipapi.co is showing the same problem again, I might just switch the script the ipinfo.io ;)

Cheers,
Marc

**Comment by curdaneta** [comment]
Thanks @i07 
Yes, it's back again!

Cheers
Ciro

**Comment by QuattroGam3r** [comment]
@i07 thanks for the update. Ipapi also seems to resolve faster than ipinfo, so kudos for reaching out to them and getting some results. I almost took the time to rewrite for an api access key, since that seems to be the way these services are heading.
